import 'app_icon_data.dart';

class AppIcons {
  // private constructor
  const AppIcons._();
  static const home = AppIconData("assets/icons/home.png");
  static const google = AppIconData("assets/icons/google.png");
  static const apple = AppIconData("assets/icons/apple.png");
  static const user = AppIconData("assets/icons/user.png");
  static const password = AppIconData("assets/icons/lock.png");
  static const activity = AppIconData("assets/icons/activity.png");
  static const add = AppIconData("assets/icons/add.png");
  static const application = AppIconData("assets/icons/application.png");
  static const approveddoc = AppIconData("assets/icons/approved_doc.png");
  static const calendar = AppIconData("assets/icons/calendar.png");
  static const call = AppIconData("assets/icons/call.png");
  static const camera = AppIconData("assets/icons/camera.png");
  static const collection = AppIconData("assets/icons/collection.png");
  static const comment = AppIconData("assets/icons/comment.png");
  static const community = AppIconData("assets/icons/community.png");
  static const credit = AppIconData("assets/icons/credit.png");
  static const cross = AppIconData("assets/icons/cross.png");
  static const delete = AppIconData("assets/icons/delete.png");
  static const discover = AppIconData("assets/icons/discover.png");
  static const download = AppIconData("assets/icons/download.png");
  static const email = AppIconData("assets/icons/email.png");
  static const filter = AppIconData("assets/icons/filter.png");
  static const heartBorder = AppIconData("assets/icons/heartBordered.png");
  static const heartFilled = AppIconData("assets/icons/heartFilled.png");
  static const like = AppIconData("assets/icons/like.png");
  static const likeCircle = AppIconData("assets/icons/likeCircle.png");
  static const likeFilled = AppIconData("assets/icons/likeFilled.png");
  static const lock = AppIconData("assets/icons/lock.png");
  static const logout = AppIconData("assets/icons/logout.png");
  static const nodocuments = AppIconData("assets/icons/nodocuments.png");
  static const notification = AppIconData("assets/icons/notification.png");
  static const payment = AppIconData("assets/icons/payment.png");
  static const pencil = AppIconData("assets/icons/pencil.png");
  static const play = AppIconData("assets/icons/play.png");
  static const profile = AppIconData("assets/icons/profile.png");
  static const rejectedDoc = AppIconData("assets/icons/rejectedDoc.png");
  static const reviewDoc = AppIconData("assets/icons/reviewDoc.png");
  static const search = AppIconData("assets/icons/search.png");
  static const share = AppIconData("assets/icons/share.png");
  static const sort = AppIconData("assets/icons/sort.png");
  static const star = AppIconData("assets/icons/star.png");
  static const starborder = AppIconData("assets/icons/star_border.png");
  static const successStories = AppIconData("assets/icons/successStories.png");
  static const upload = AppIconData("assets/icons/upload.png");
  static const totalSum = AppIconData("assets/icons/totalSum.png");
  static const spread = AppIconData("assets/icons/spread.png");
  static const privacy = AppIconData("assets/icons/privacy.png");
  static const terms = AppIconData("assets/icons/terms.png");
  static const pdf = AppIconData("assets/icons/pdf.png");
  static const write = AppIconData("assets/icons/write.png");
  static const degree = AppIconData("assets/icons/degree.png");
  static const openbook = AppIconData("assets/icons/openbook.png");
  static const sun = AppIconData("assets/icons/sun.png");
  static const verticlespread = AppIconData("assets/icons/verticlespread.png");
  static const applyVisa = AppIconData("assets/icons/apply_visa.png");
  static const counselorChat = AppIconData("assets/icons/counselor_chat.png");
  static const send = AppIconData("assets/icons/send.png");
  static const image = AppIconData("assets/icons/image.png");
  static const copyright = AppIconData("assets/icons/copyright.png");
}
